### ISSUE TITLE
Fluentbit container keeps restarting: pgsql - remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by skinnynoizze** [ritual-net/infernet-node#13]
Container keeps restarting due to this error:

fluentbit-1  | [2024/03/02 10:19:44] [error] [output:pgsql:pgsql.1] failed connecting to host=meta-sink.ritual.net with error: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by stelios-ritual** [comment]
This issue has been resolved. Thanks or flagging.
